@startuml

agent Client
agent Server
json register {
	"type": "register",
	"username": "demo",
	"passwordsha1": "9ad4cf12ea8c7c42000a7af92864e80e807a0718"
}
json login {
	"type": "login",
	"username": "demo",
	"passwordsha1": "9ad4cf12ea8c7c42000a7af92864e80e807a0718"
}
database Database

Client -> register
register -> Server
Client -> login
login -> Server
Server -> Database

@enduml