CREATE TABLE IF NOT EXISTS User (
	UserID INTEGER PRIMARY KEY AUTOINCREMENT,
	UserName TEXT UNIQUE NOT NULL,
	UserPasswordSha1 BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS Room (
	RoomID INTEGER PRIMARY KEY AUTOINCREMENT,
	RoomName TEXT,
	RoomCreateTime NUMERIC NOT NULL
	-- RoomOwner INTEGER REFERENCES User(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
	-- RoomDescription TEXT
);

CREATE TABLE IF NOT EXISTS Msg (
	MsgID INTEGER PRIMARY KEY AUTOINCREMENT,
	MsgSender INTEGER REFERENCES User(UserID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	RoomID INTEGER REFERENCES Room(RoomID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	MsgType INTEGER NOT NULL,
	MsgContent TEXT NOT NULL,
	MsgSendtime NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS RoomMember (
	RoomID INTEGER REFERENCES Room(RoomID) ON DELETE CASCADE ON UPDATE CASCADE,
	UserID INTEGER REFERENCES User(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
	-- LastRead INTEGER REFERENCES Msg(MsgID)
	PRIMARY KEY (RoomID, UserID)
);

CREATE TABLE IF NOT EXISTS RoomAdmin (
	RoomID INTEGER REFERENCES Room(RoomID) ON DELETE CASCADE ON UPDATE CASCADE,
	UserID INTEGER REFERENCES User(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (RoomID, UserID)
);

-- CREATE TABLE IF NOT EXISTS UserBlock (
-- 	RoomID INTEGER REFERENCES Room(RoomID) ON DELETE CASCADE ON UPDATE CASCADE,
-- 	UserID INTEGER REFERENCES User(UserID) ON DELETE CASCADE ON UPDATE CASCADE
-- );