# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ChatListItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatListItemWidget(object):
    def setupUi(self, ChatListItemWidget):
        ChatListItemWidget.setObjectName("ChatListItemWidget")
        ChatListItemWidget.resize(281, 71)
        ChatListItemWidget.setMinimumSize(QtCore.QSize(281, 71))
        ChatListItemWidget.setMaximumSize(QtCore.QSize(281, 71))
        ChatListItemWidget.setAutoFillBackground(False)
        ChatListItemWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(245, 245, 245)\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(ChatListItemWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(ChatListItemWidget)
        self.frame.setMinimumSize(QtCore.QSize(282, 72))
        self.frame.setMaximumSize(QtCore.QSize(282, 72))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.chatProf = QtWidgets.QLabel(self.frame)
        self.chatProf.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.chatProf.setStyleSheet("QLabel{\n"
"    border-radius: 50%\n"
"}")
        self.chatProf.setText("")
        self.chatProf.setPixmap(QtGui.QPixmap("./../graphSource/profPhoto.jpg"))
        self.chatProf.setScaledContents(True)
        self.chatProf.setObjectName("chatProf")
        self.chatName = QtWidgets.QLabel(self.frame)
        self.chatName.setGeometry(QtCore.QRect(80, 13, 58, 16))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(14)
        self.chatName.setFont(font)
        self.chatName.setObjectName("chatName")
        self.recentMsg = QtWidgets.QLabel(self.frame)
        self.recentMsg.setGeometry(QtCore.QRect(80, 42, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        self.recentMsg.setFont(font)
        self.recentMsg.setObjectName("recentMsg")
        self.msgTime = QtWidgets.QLabel(self.frame)
        self.msgTime.setGeometry(QtCore.QRect(180, 10, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        self.msgTime.setFont(font)
        self.msgTime.setObjectName("msgTime")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(ChatListItemWidget)
        QtCore.QMetaObject.connectSlotsByName(ChatListItemWidget)

    def retranslateUi(self, ChatListItemWidget):
        _translate = QtCore.QCoreApplication.translate
        ChatListItemWidget.setWindowTitle(_translate("ChatListItemWidget", "Form"))
        self.chatName.setText(_translate("ChatListItemWidget", "Paimon"))
        self.recentMsg.setText(_translate("ChatListItemWidget", "<html><head/><body><p><span style=\" color:#a9a9a9;\">rec_msg_hello~</span></p></body></html>"))
        self.msgTime.setText(_translate("ChatListItemWidget", "<html><head/><body><p align=\"right\"><span style=\" color:#a9a9a9;\">2023/8/26</span></p></body></html>"))
