# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatBubbleForUsr.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatBubbles(object):
    def setupUi(self):
        self.setObjectName("ChatBubbles")
        self.resize(541, 94)
        self.setMinimumSize(QtCore.QSize(400, 0))
        self.setStyleSheet("QWidget{\n"
            "background-color: rgb(255, 255, 255)\n"
            "}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.nameAndTime = QtWidgets.QLabel(self)
        self.nameAndTime.setMinimumSize(QtCore.QSize(100, 21))
        self.nameAndTime.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(14)
        self.nameAndTime.setFont(font)
        self.nameAndTime.setObjectName("nameAndTime")
        self.horizontalLayout_2.addWidget(self.nameAndTime)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.msgText = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        self.msgText.setFont(font)
        self.msgText.setStyleSheet("QLabel {\n"
            "    border-radius: 10px; /* Adjust the radius value as needed */\n"
            "    background-color:rgb(232, 253, 255);/* Set the background color */\n"
            "    padding: 5px; /* Add some padding to the label */\n"
            "}")
        self.msgText.setObjectName("msgText")
        self.horizontalLayout_3.addWidget(self.msgText)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.profPhoto = QtWidgets.QLabel(self)
        self.profPhoto.setMinimumSize(QtCore.QSize(51, 51))
        self.profPhoto.setMaximumSize(QtCore.QSize(51, 51))
        self.profPhoto.setText("")
        self.profPhoto.setPixmap(QtGui.QPixmap("../graphSource/profPhoto.jpg"))
        self.profPhoto.setScaledContents(True)
        self.profPhoto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.profPhoto.setObjectName("profPhoto")
        self.verticalLayout_2.addWidget(self.profPhoto)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.setStretch(1, 40)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)

        
        # QtCore.QMetaObject.connectSlotsByName(ChatBubbles)

        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("ChatBubbles", "Form"))
        self.nameAndTime.setText(_translate("ChatBubbles", "2023/08/29  10:59   Name"))
        self.msgText.setText(_translate("ChatBubbles", "111111111111111111"))
