# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MemberListItemWidget(object):
    def setupUi(self, MemberListItemWidget):
        MemberListItemWidget.setObjectName("MemberListItemWidget")
        MemberListItemWidget.resize(191, 72)
        MemberListItemWidget.setMinimumSize(QtCore.QSize(191, 0))
        MemberListItemWidget.setMaximumSize(QtCore.QSize(191, 16777215))
        MemberListItemWidget.setStyleSheet("QWidget{\n"
"background-color: rgb(244, 244, 244)\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(MemberListItemWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(MemberListItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(192)
        sizePolicy.setVerticalStretch(74)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(193, 74))
        self.frame.setMaximumSize(QtCore.QSize(193, 74))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.memberProfPhoto = QtWidgets.QLabel(self.frame)
        self.memberProfPhoto.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.memberProfPhoto.setText("")
        self.memberProfPhoto.setPixmap(QtGui.QPixmap("./../graphSource/profPhoto.jpg"))
        self.memberProfPhoto.setScaledContents(True)
        self.memberProfPhoto.setObjectName("memberProfPhoto")
        self.memberName = QtWidgets.QLabel(self.frame)
        self.memberName.setGeometry(QtCore.QRect(70, 16, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        self.memberName.setFont(font)
        self.memberName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.memberName.setObjectName("memberName")
        self.memberID = QtWidgets.QLabel(self.frame)
        self.memberID.setGeometry(QtCore.QRect(70, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        self.memberID.setFont(font)
        self.memberID.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.memberID.setObjectName("memberID")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(MemberListItemWidget)
        QtCore.QMetaObject.connectSlotsByName(MemberListItemWidget)

    def retranslateUi(self, MemberListItemWidget):
        _translate = QtCore.QCoreApplication.translate
        MemberListItemWidget.setWindowTitle(_translate("MemberListItemWidget", "MemberListItemWidget"))
        self.memberName.setText(_translate("MemberListItemWidget", "Name"))
        self.memberID.setText(_translate("MemberListItemWidget", "ID: 1231231231"))
